# Generated by Django 3.1.7 on 2021-05-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Publisher name', max_length=50)),
                ('website', models.URLField(help_text="Publisher's website address")),
                ('email', models.EmailField(help_text="Publisher's email address", max_length=254)),
            ],
        ),
    ]
